
skillMetadata:
  sections:
    - name: Request
      fields:
        - name: url
          type: text
          label: Url to make request to (can include get params)
          value: "http://0.0.0.0/"
